<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Landlord Diary Export</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            font-size: 18px;
            font-weight: bold;
            color: #2c3e50;
            text-align: center;
            margin-bottom: 10px;
        }
        .section-title {
            background-color: #d9edf7;
            color: #31708f;
            font-weight: bold;
            padding: 6px;
            margin-top: 20px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #999;
            padding: 6px;
            text-align: center;
        }
        th {
            background-color: #e6f2ff;
            color: #003366;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <div class="header">ESTMAN — Landlord Diary</div>

    <p><strong>Generated by:</strong> {{ $user->firstname }} {{ $user->lastname }}<br>
       <strong>Period:</strong> {{ $from }} to {{ $to }}</p>

    {{-- Summary Table --}}
    @php
        $total = $landlords->count();
        $active = $landlords->filter(fn($l) => strtolower(trim($l->isactive ?? $l->approval)) === 'y')->count();
        $inactive = $total - $active;
    @endphp

    <div class="section-title">Summary</div>
    <table>
        <thead>
            <tr>
                <th>Total Landlords</th>
                <th>Active</th>
                <th>Not Active</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $total }}</td>
                <td>{{ $active }}</td>
                <td>{{ $inactive }}</td>
            </tr>
        </tbody>
    </table>

    {{-- Detailed Landlord Table --}}
    <div class="section-title">Landlord Details</div>
    <table>
        <thead>
            <tr>
                <th>Type</th>
                <th>Name</th>
                <th>TIN Number</th>
                <th>Cell</th>
                <th>Email</th>
                <th>Tel</th>
                <th># Properties</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($landlords as $landlord)
            <tr>
                <td>{{ ucfirst($landlord->clienttypeid) }}</td>
                <td>
                    @if(strtolower($landlord->clienttypeid) === 'individual')
                        {{ $landlord->firstname ?? '—' }} {{ $landlord->lastname ?? '' }}
                    @else
                        {{ $landlord->companyname ?? '—' }}
                    @endif
                </td>
                <td>{{ $landlord->companynumber ?? '—' }}</td>
                <td>{{ $landlord->cell ?? '—' }}</td>
                <td>{{ $landlord->email ?? '—' }}</td>
                <td>{{ $landlord->tel ?? '—' }}</td>
                <td>{{ $landlord->property_count ?? '—' }}</td>
                <td>
                    @if(strtolower(trim($landlord->isactive ?? $landlord->approval)) === 'y')
                        Active
                    @else
                        Not Active
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

</body>
</html>
